### ISSUE TITLE
Dynamically filter responsive variants

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/codevisor#5]
`sm`, `md`, `focus`, etc. can be found by `.reduce`ing all of the `cssRules`.

**Comment by ericclemmons** [comment]
I don't even see `sm:` `md:` etc. at all!

**Comment by ericclemmons** [comment]
UI-wise, I'm thinking a `sm:`, `md:` set of radio buttons.

**Comment by ericclemmons** [comment]
That's better for variants such as `:hover`, but it could be possible to read the `CSSMediaStylesheet` and determine what width `sm:`, `xl:` should be.

That way, simply resizing (`onResize`) the browser window would activate the base styles _plus_ that variant.

(The only caveat is that the toolbar affects the width of the page for the user, making media queries trickier without putting the page in its own frame).

**Comment by cdonohue** [comment]
@ericclemmons you might try having the toolbar be along the bottom of the screen. 

This would solve for the horizontal viewport media issue above and also allow for listing the matches class names in an overflowing row as pulls to select from. 

This would probably mean that the toolbar is in two side-by-side sections. Left side with the applied classes and the right with search results for discovery of additional classes.

**Comment by ericclemmons** [comment]
Will let #25 solve this.
